# Generated by Django 6.0.6 on 2026-06-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_candidate_education_candidate_expected_salary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="education",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="experience",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="skills",
            field=models.TextField(),
        ),
    ]
