# Generated by Django 6.0.6 on 2026-07-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_job_experience_job_job_type_job_location_job_salary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
