# Generated by Django 6.0.6 on 2026-07-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_savedjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
