# Generated by Django 6.0.6 on 2026-07-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_emaillog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[("SENT", "Sent"), ("FAILED", "Failed")],
                default="SENT",
                max_length=20,
            ),
        ),
    ]
