# Generated by Django 6.0.6 on 2026-07-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_emaillog_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate'], name='core_applic_candida_43c5dc_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job'], name='core_applic_job_id_0e9ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='core_applic_status_148db8_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='core_job_status_4b2344_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='core_job_locatio_a1880e_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type'], name='core_job_job_typ_5d260f_idx'),
        ),
    ]
