# Generated by Django 6.0.6 on 2026-07-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_aianswer_ai_feedback_aianswer_completeness_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aianswer",
            name="evaluated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
