from django.urls import path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    AdminAPIView,
    AdminBillingHistoryAPIView,
    AdminRefundAPIView,
    AdminTransactionListAPIView,
    AIAnalyticsAPIView,
    AnswerScoreAPIView,
    ApplicantListAPIView,
    ApplicationCountAPIView,
    ApplicationHistoryAPIView,
    ApplicationStatusUpdateAPIView,
    ApplicationTimelineAPIView,
    AppliedJobsAPIView,
    ApplyJobAPIView,
    AuditLogAPIView,
    AuthTestAPIView,
    AvailabilityListAPIView,
    BookInterviewAPIView,
    CandidateDashboardAPIView,
    CandidateProfileAPIView,
    CandidateReportAPIView,
    CapturePaymentAPIView,
    ConversionRatioAPIView,
    CreateAvailabilitySlotAPIView,
    CreatePaymentOrderAPIView,
    DailyRevenueAPIView,
    EmployerApprovalAPIView,
    EmployerJobsAPIView,
    EmployerProfileAPIView,
    FeaturedJobAPIView,
    HiringFunnelAPIView,
    InterviewStatusAPIView,
    JobActivityAPIView,
    JobCreateAPIView,
    JobListAPIView,
    JobPerformanceAPIView,
    JobStatusAPIView,
    JobUpdateAPIView,
    LatestJobAPIView,
    LoginAPIView,
    LogoutAPIView,
    MonthlyRevenueAPIView,
    PlanWiseRevenueAPIView,
    PlatformStatsAPIView,
    ProcessApplicationsAPIView,
    RankedCandidatesAPIView,
    RazorpayWebhookAPIView,
    RecommendedJobsAPIView,
    RemoveSpamJobAPIView,
    ResumeParserAPIView,
    RevenueSummaryAPIView,
    SavedJobsAPIView,
    SaveJobAPIView,
    SendInterviewRemindersAPIView,
    ShortlistRatioAPIView,
    SignupAPIView,
    SubmitAnswerAPIView,
    SubscriptionStatusAPIView,
    UpdateApplicationStatusAPIView,
    UserBlockAPIView,
    UserTestAPIView,
    VerifyPaymentAPIView,
)

urlpatterns = [
    path("signup/", SignupAPIView.as_view()),
    path("login/", LoginAPIView.as_view()),
    path("jobs/", JobListAPIView.as_view()),
    path("jobs/create/", JobCreateAPIView.as_view()),
    path("users/test/", UserTestAPIView.as_view()),
    path("admin/test/", AdminAPIView.as_view()),
    path("candidate/profile/", CandidateProfileAPIView.as_view()),
    path("employer/profile/", EmployerProfileAPIView.as_view()),
    path("jobs/<int:pk>/update/", JobUpdateAPIView.as_view()),
    path("jobs/<int:pk>/status/", JobStatusAPIView.as_view()),
    path("jobs/featured/", FeaturedJobAPIView.as_view()),
    path("jobs/latest/", LatestJobAPIView.as_view()),
    path("jobs/<int:pk>/apply/", ApplyJobAPIView.as_view()),
    path("applications/", ApplicationHistoryAPIView.as_view()),
    path("applications/jobs/", AppliedJobsAPIView.as_view()),
    path("applications/<int:pk>/status/", ApplicationStatusUpdateAPIView.as_view()),
    path("employer/jobs/", EmployerJobsAPIView.as_view()),
    path("jobs/<int:pk>/applicants/", ApplicantListAPIView.as_view()),
    path("jobs/<int:pk>/analytics/", ApplicationCountAPIView.as_view()),
    path("jobs/<int:pk>/shortlist-ratio/", ShortlistRatioAPIView.as_view()),
    path("jobs/<int:pk>/save/", SaveJobAPIView.as_view()),
    path("saved-jobs/", SavedJobsAPIView.as_view()),
    path("candidate/dashboard/", CandidateDashboardAPIView.as_view()),
    path("applications/timeline/", ApplicationTimelineAPIView.as_view()),
    path("jobs/recommended/", RecommendedJobsAPIView.as_view()),
    path("applications/interview-status/", InterviewStatusAPIView.as_view()),
    path("employers/<int:pk>/approve/", EmployerApprovalAPIView.as_view()),
    path("users/<int:pk>/block/", UserBlockAPIView.as_view()),
    path("admin/platform-stats/", PlatformStatsAPIView.as_view()),
    path("admin/job-activity/", JobActivityAPIView.as_view()),
    path("jobs/<int:pk>/remove/", RemoveSpamJobAPIView.as_view()),
    path("admin/audit-logs/", AuditLogAPIView.as_view()),
    path("resume/parse/", ResumeParserAPIView.as_view()),
    path("jobs/<int:pk>/ranked-candidates/", RankedCandidatesAPIView.as_view()),
    path(
        "applications/<int:pk>/update-status/",
        UpdateApplicationStatusAPIView.as_view(),
        name="update-application-status",
    ),
    path(
        "applications/process/",
        ProcessApplicationsAPIView.as_view(),
    ),
    path(
        "ai-answer/<int:answer_id>/submit/",
        SubmitAnswerAPIView.as_view(),
    ),
    path(
        "ai-answer/<int:pk>/score/",
        AnswerScoreAPIView.as_view(),
    ),
    path(
        "availability/create/",
        CreateAvailabilitySlotAPIView.as_view(),
    ),
    path(
        "availability/",
        AvailabilityListAPIView.as_view(),
    ),
    path(
        "interview/book/",
        BookInterviewAPIView.as_view(),
    ),
    path(
        "interviews/send-reminders/",
        SendInterviewRemindersAPIView.as_view(),
    ),
    path(
        "applications/<int:pk>/report/",
        CandidateReportAPIView.as_view(),
    ),
    path(
        "analytics/funnel/",
        HiringFunnelAPIView.as_view(),
    ),
    path(
        "analytics/jobs/",
        JobPerformanceAPIView.as_view(),
    ),
    path(
        "analytics/conversion/",
        ConversionRatioAPIView.as_view(),
    ),
    path(
        "analytics/ai/",
        AIAnalyticsAPIView.as_view(),
    ),
    path(
        "payments/create-order/",
        CreatePaymentOrderAPIView.as_view(),
    ),
    path(
        "payments/verify/",
        VerifyPaymentAPIView.as_view(),
    ),
    path(
        "payments/capture/",
        CapturePaymentAPIView.as_view(),
    ),
    path(
        "payments/webhook/",
        RazorpayWebhookAPIView.as_view(),
    ),
    path(
        "subscription/status/",
        SubscriptionStatusAPIView.as_view(),
    ),
    path("auth-test/", AuthTestAPIView.as_view()),
    path(
        "admin/billing/transactions/",
        AdminTransactionListAPIView.as_view(),
    ),
    path(
        "admin/billing/history/",
        AdminBillingHistoryAPIView.as_view(),
    ),
    path(
        "admin/billing/revenue/daily/",
        DailyRevenueAPIView.as_view(),
    ),
    path(
        "admin/billing/revenue/monthly/",
        MonthlyRevenueAPIView.as_view(),
    ),
    path(
        "admin/billing/revenue/plans/",
        PlanWiseRevenueAPIView.as_view(),
    ),
    path(
        "admin/billing/revenue/summary/",
        RevenueSummaryAPIView.as_view(),
    ),
    path(
        "admin/billing/transactions/<int:pk>/refund/",
        AdminRefundAPIView.as_view(),
    ),
    path("token/refresh/", TokenRefreshView.as_view()),
    path("logout/", LogoutAPIView.as_view()),
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
]
