from django.urls import path

from .views import (
    SignupAPIView,
    LoginAPIView,
    JobListAPIView,
    JobCreateAPIView,
    UserTestAPIView,
    AdminAPIView,
    CandidateProfileAPIView,
    EmployerProfileAPIView,
    JobUpdateAPIView,
    JobStatusAPIView,
    FeaturedJobAPIView,
    LatestJobAPIView,
    ApplyJobAPIView,
    ApplicationHistoryAPIView,
    AppliedJobsAPIView,
    ApplicationStatusUpdateAPIView,
    EmployerJobsAPIView,
    ApplicantListAPIView,
    ApplicationCountAPIView,
    ShortlistRatioAPIView,
    SaveJobAPIView,
    SavedJobsAPIView,
    CandidateDashboardAPIView,
    ApplicationTimelineAPIView,
    RecommendedJobsAPIView,
    InterviewStatusAPIView,
    EmployerApprovalAPIView,
    UserBlockAPIView,
    PlatformStatsAPIView,
    JobActivityAPIView,
    RemoveSpamJobAPIView,
    AuditLogAPIView,
)
urlpatterns = [
    path('signup/', SignupAPIView.as_view()),
    path('login/', LoginAPIView.as_view()),
    path('jobs/', JobListAPIView.as_view()),
    path('jobs/create/', JobCreateAPIView.as_view()),
    path('users/test/', UserTestAPIView.as_view()),
    path('admin/test/', AdminAPIView.as_view()),
    path('candidate/profile/', CandidateProfileAPIView.as_view()),
    path('employer/profile/', EmployerProfileAPIView.as_view()),
    path("jobs/<int:pk>/update/", JobUpdateAPIView.as_view()),
    path("jobs/<int:pk>/status/", JobStatusAPIView.as_view()),
    path("jobs/featured/", FeaturedJobAPIView.as_view()),
    path("jobs/latest/", LatestJobAPIView.as_view()),
    path("jobs/<int:pk>/apply/", ApplyJobAPIView.as_view()),
    path("applications/", ApplicationHistoryAPIView.as_view()),
    path("applications/jobs/", AppliedJobsAPIView.as_view()),
    path("applications/<int:pk>/status/", ApplicationStatusUpdateAPIView.as_view()),
    path("employer/jobs/",EmployerJobsAPIView.as_view()),
    path("jobs/<int:pk>/applicants/",ApplicantListAPIView.as_view()),
    path("jobs/<int:pk>/analytics/",ApplicationCountAPIView.as_view()),
    path("jobs/<int:pk>/shortlist-ratio/",ShortlistRatioAPIView.as_view()),
    path("jobs/<int:pk>/save/",SaveJobAPIView.as_view()),
    path("saved-jobs/",SavedJobsAPIView.as_view()),
    path("candidate/dashboard/",CandidateDashboardAPIView.as_view()),
    path("applications/timeline/",ApplicationTimelineAPIView.as_view()),
    path("jobs/recommended/",RecommendedJobsAPIView.as_view()),
    path("applications/interview-status/",InterviewStatusAPIView.as_view()),
    path("employers/<int:pk>/approve/",EmployerApprovalAPIView.as_view()),
    path("users/<int:pk>/block/",UserBlockAPIView.as_view()),
    path("admin/platform-stats/",PlatformStatsAPIView.as_view()),
    path("admin/job-activity/",JobActivityAPIView.as_view()),
    path("jobs/<int:pk>/remove/",RemoveSpamJobAPIView.as_view()),
    path("admin/audit-logs/",AuditLogAPIView.as_view()),
]